# |-------------------------------------------------------------------------------------------------|
# |                               _____ _                 __  __                                    |
# |                              / ____| |               |  \/  |                                   |
# |                             | |  __| | _____      __ | \  / | ___                               |
# |                             | | |_ | |/ _ \ \ /\ / / | |\/| |/ _ \                              |
# |                             | |__| | | (_) \ V  V /  | |  | |  __/                              |
# |                              \_____|_|\___/ \_/\_/   |_|  |_|\___|                              |
# |                                                                                                 |
# |                                   GitHub.com/Monjhall/GlowMe                                    |
# |                                                                                                 |
# |                               Use material names from this list:                                |
# |                         https://jd.bukkit.org/org/bukkit/Material.html                          |
# |                                 Use color names from this list:                                 |
# |                         https://jd.bukkit.org/org/bukkit/ChatCOLOR.html                         |
# |                               Use teleport causes from this list:                               |
# |      https://jd.bukkit.org/org/bukkit/event/player/PlayerTeleportEvent.TeleportCause.html       |
# |                                Use entity types from this list:                                 |
# |                     https://jd.bukkit.org/org/bukkit/entity/EntityType.html                     |
# |           All durations should be set between 0-1500, using -1 for infinite duration.           |
# |     Having a <player> or <p> in your message will be replaced with the player name in-game.     |
# |  Having a <cause> or <c> in your message will be replaced with the cause of the event in-game.  |
# |                                                                                                 |
# |-------------------------------------------------------------------------------------------------|
#
ITEMCRAFT:
  DIAMOND_SWORD:
    ACTION: ANNOUNCEGLOW
    MESSAGE: "<p> has crafted a diamond sword!"
    GLOWSETTINGS:
      COLOR: AQUA
      DURATION: 30
  DIAMOND_HOE:
    ACTION: GLOW
    MESSAGE: "<p> has crafted a diamond hoe!"
    GLOWSETTINGS:
      COLOR: GREEN
      DURATION: 45
ITEMCONSUME:
  GOLDEN_APPLE:
    ACTION: ANNOUNCEGLOW
    MESSAGE: "<p> has eaten a golden apple!"
    GLOWSETTINGS:
      COLOR: YELLOW
      DURATION: 45
  BREAD:
    ACTION: ANNOUNCECLEANSE
    MESSAGE: "<p> has cleansed their glow with bread!"
ITEMPICKUP:
  DIAMOND:
    ACTION: GLOW
    GLOWSETTINGS:
      COLOR: BLUE
      DURATION: 30
TELEPORT:
  ENDER_PEARL:
    ACTION: GLOW
    GLOWSETTINGS:
      COLOR: DARK_PURPLE
      DURATION: 30
ENTITYKILLED:
  PLAYER:
    ACTION: GLOW
    GLOWSETTINGS:
      COLOR: RED
      DURATION: 60
  SKELETON:
    ACTION: ANNOUNCEGLOW
    MESSAGE: "<p> has slain a skeleton!"
    GLOWSETTINGS:
      COLOR: BLACK
      DURATION: 30
  CREEPER:
    ACTION: CLEANSE