# |-------------------------------------------------------------------------------------------------|
# |                               _____ _                 __  __                                    |
# |                              / ____| |               |  \/  |                                   |
# |                             | |  __| | _____      __ | \  / | ___                               |
# |                             | | |_ | |/ _ \ \ /\ / / | |\/| |/ _ \                              |
# |                             | |__| | | (_) \ V  V /  | |  | |  __/                              |
# |                              \_____|_|\___/ \_/\_/   |_|  |_|\___|                              |
# |                                                                                                 |
# |                                   GitHub.com/Monjhall/GlowMe                                    |
# |                                                                                                 |
# |                               Use material names from this list:                                |
# |                         https://jd.bukkit.org/org/bukkit/Material.html                          |
# |                                 Use color names from this list:                                 |
# |                         https://jd.bukkit.org/org/bukkit/ChatColor.html                         |
# |                               Use teleport causes from this list:                               |
# |      https://jd.bukkit.org/org/bukkit/event/player/PlayerTeleportEvent.TeleportCause.html       |
# |                                Use entity types from this list:                                 |
# |                     https://jd.bukkit.org/org/bukkit/entity/EntityType.html                     |
# |           All durations should be set between 0-1500, using -1 for infinite duration.           |
# |                                                                                                 |
# |-------------------------------------------------------------------------------------------------|
#
ItemCraft:
  DIAMOND_SWORD:
    Color: AQUA
    Duration: 30
  DIAMOND_HOE:
    Color: BLUE
    Duration: 15


ItemConsume:
  GOLDEN_APPLE:
    Color: YELLOW
    Duration: 30
  BREAD:
    Color: GOLD
    Duration: 30
    

ItemPickup:
  DIAMOND:
    Color: AQUA
    Duration: 30
    

Teleport:
  ENDER_PEARL:
    Color: DARK_PURPLE
    Duration: 30
    

EntityKilled:
  PLAYER:
    Color: RED
    Duration: 30
  SKELETON:
    Color: BLACK
    Duration: 30