name: GlowMe
main: io.github.monjhall.glowme.GlowMe
version: 0.1.6
author: Monjhall

commands:
  glow:
    description: This command's function body needs to be filled out.
    usage: /<command> [player] [duration] [color]
    permission: glowme.glow
    permission-message: You don't have <permission>