name: GlowMe
main: io.github.monjhall.glowme.GlowMe
version: 0.7.0
author: Monjhall

commands:
  glow:
    description: Applies a glow to a specified player.
    usage: /<command> [player] [color] [duration]
    permission: glowme.glow
    permission-message: You don't have <permission>.
  clearglow:
    description: Clears glow off of the specified player.
    usage: /<command> [player]
    permission: glowme.clearglow
    permission-message: You don't have <permission>.
  setglowconfig:
    description: Sets a glow configuration in the file.
    usage: /<command> [Event] [Material/TeleportCause/Entity] [Color] [Duration]
    permission: glowme.config
    permission-message: You don't have <permission>.

permissions:
  glowme.*:
    description: Gives access to all glowme commands.
    children:
      glowme.glow: true
      glowme.clearglow: true
      glowme.config: true
  glowme.glow:
    description: Gives access to the command for glow setting.
    default: op
  glowme.clearglow:
    description: Gives access to the command for clearing your glow.
    default: op
  glowme.config:
    description: Gives access to the command for modifying the config file.
    default: op